command:
  - python
  - boot.py

env:
  - name: SUPERSET_HOME
    value: "/home/app/superset"
  - name: SUPERSET_ADMIN_USERNAME
    value: "admin"
  - name: SUPERSET_ADMIN_PASSWORD
    value: "admin"
  - name: SUPERSET_ADMIN_EMAIL
    value: "mexmarv@gmail.com"
  - name: DATABRICKS_HOST
    value: "https://DATABRICKS_HOST"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/DATABRICKS_PAT"
  - name: DATABRICKS_TOKEN
    value: "DATABRICKS_TOKEN"
